# Python për Data Science – Sesioni 2
## NumPy & Pandas: Punë me të Dhëna Tabelare

**Fokus i sesionit**
- NumPy: arrays dhe operacione numerike
- Pandas: DataFrame & Series
- Eksplorimi i të dhënave 
- Zgjedhja e kolonave dhe filtrimi i rreshtave

## Lidhja me Sesionin 1

Në sesionin e kaluar mësuam bazat e Python:
- variabla
- tipe të dhënash
- lista

Sot kalojmë në struktura të përdorura realisht në Data Science:
- **NumPy** për llogaritje numerike
- **Pandas** për punë me tabela (si Excel)

Import libraries

Nëse shfaqet ndonjë gabim `ModuleNotFoundError`, instaloni paketat me:

- **macOS**: `pip install numpy pandas`
- **Windows**: `pip install numpy pandas`

In [1]:
import numpy as np
import pandas as pd

## NumPy

NumPy është një **Python library** për punë me data numerike.
Struktura kryesore quhet **array** dhe është e optimizuar për llogaritje.

## NumPy Arrays

Një NumPy array:
- është koleksion vlerash numerike
- zakonisht me të njëjtin tip
- është i shpejtë për llogaritje

Shembull: temperatura ditore.

In [2]:
temperaturat = np.array([20, 22, 19, 21, 23, 24, 18])
temperaturat

array([20, 22, 19, 21, 23, 24, 18])

In [3]:
print("Mesatarja:", temperaturat.mean())
print("Minimumi:", temperaturat.min())
print("Maksimumi:", temperaturat.max())
print("Numri i vlerave:", temperaturat.size)

Mesatarja: 21.0
Minimumi: 18
Maksimumi: 24
Numri i vlerave: 7

## Pse jo vetëm listat?

Listat janë shumë të mira për shembuj të thjeshtë.
Por për analiza numerike me shumë të dhëna:

- NumPy arrays janë më të shpejtë
- janë të optimizuar për llogaritje
- punojnë mirë me shumë vlera njëkohësisht

(Në praktikë, shumë operacione në Pandas bazohen në NumPy.)

In [4]:
# Shembull: mbledhja e listave
temp_list1 = [21, 23, 20, 22]
temp_list2 = [24, 25, 19, 20]

temp_list1+temp_list2

[21, 23, 20, 22, 24, 25, 19, 20]

In [5]:
# Shembull: mbledhja e array
temp_array1 = np.array(temp_list1)
temp_array2 = np.array(temp_list2)

temp_array1 + temp_array2

array([45, 48, 39, 42])

In [6]:
# Shembull: rrisim çdo temperaturë me +1 gradë
temperaturat_plus1 = temperaturat + 1
temperaturat_plus1

array([21, 23, 20, 22, 24, 25, 19])

In [7]:
# Diferenca mes vlerave dhe mesatares
diferenca = temperaturat - temperaturat.mean()
diferenca

array([-1.,  1., -2.,  0.,  2.,  3., -3.])

## Pandas

Pandas është Python library më e përdorur për analiza të të dhënave.
Ajo na lejon të punojmë me **tabela** të quajtura **DataFrame** (si Excel).

## DataFrame dhe Series

- **DataFrame**: tabelë me rreshta dhe kolona
- **Series**: një kolonë e vetme e një DataFrame

In [8]:
data = {
    "Emri": ["Ana", "Jon", "Sara", "Elio", "Dora", "Ardit"],
    "Mosha": [25, 30, 22, 28, 35, 27],
    "Departamenti": ["IT", "Finance", "IT", "HR", "Finance", "IT"],
    "Paga": [800, 1200, 700, 1000, 1500, 950]
}

df = pd.DataFrame(data)
df

    Emri  Mosha Departamenti  Paga
0    Ana     25           IT   800
1    Jon     30      Finance  1200
2   Sara     22           IT   700
3   Elio     28           HR  1000
4   Dora     35      Finance  1500
5  Ardit     27           IT   950

## Eksplorimi i të dhënave

Hapi i parë në çdo analizë është të kuptojmë dataset-in:
- si duket tabela?
- çfarë kolonash kemi?
- çfarë tipesh të dhënash?
- statistika bazë

In [9]:
df.head()

   Emri  Mosha Departamenti  Paga
0   Ana     25           IT   800
1   Jon     30      Finance  1200
2  Sara     22           IT   700
3  Elio     28           HR  1000
4  Dora     35      Finance  1500

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Emri          6 non-null      str
 1   Mosha         6 non-null      int64
 2   Departamenti  6 non-null      str
 3   Paga          6 non-null      int64
dtypes: int64(2), str(2)
memory usage: 324.0 bytes

In [11]:
df.describe()

           Mosha         Paga
count   6.000000     6.000000
mean   27.833333  1025.000000
std     4.445972   289.395923
min    22.000000   700.000000
25%    25.500000   837.500000
50%    27.500000   975.000000
75%    29.500000  1150.000000
max    35.000000  1500.000000

In [12]:
len(df)

6

## Zgjedhja e kolonave

Shpesh na duhen vetëm disa kolona.
Kolonat i zgjedhim sipas emrit të tyre.

In [13]:
df

    Emri  Mosha Departamenti  Paga
0    Ana     25           IT   800
1    Jon     30      Finance  1200
2   Sara     22           IT   700
3   Elio     28           HR  1000
4   Dora     35      Finance  1500
5  Ardit     27           IT   950

In [14]:
df["Paga"]

0     800
1    1200
2     700
3    1000
4    1500
5     950
Name: Paga, dtype: int64

In [15]:
df = df[["Emri", "Departamenti", "Paga"]]

## Filtrimi i rreshtave

Filtrimi na lejon të nxjerrim vetëm rreshtat që na interesojnë,
p.sh. vetëm punonjësit me pagë më të lartë se një kufi.

In [16]:
df[df["Paga"] > 900]

    Emri Departamenti  Paga
1    Jon      Finance  1200
3   Elio           HR  1000
4   Dora      Finance  1500
5  Ardit           IT   950

In [17]:
df[df["Departamenti"] == "IT"]

    Emri Departamenti  Paga
0    Ana           IT   800
2   Sara           IT   700
5  Ardit           IT   950

## Renditja e rreshtave

Renditja na lejon të radhisim rreshtat sipas vlerave që na interesojnë,
p.sh. duke shfaqur punonjësit me pagën më të lartë në fillim të tabelës.

In [18]:
df.sort_values("Paga", ascending=False)

    Emri Departamenti  Paga
4   Dora      Finance  1500
1    Jon      Finance  1200
3   Elio           HR  1000
5  Ardit           IT   950
0    Ana           IT   800
2   Sara           IT   700

##  Vlera që mungojnë
Do të simulojmë një pagë që mungon dhe do ta trajtojmë.

In [19]:
df_with_nan = pd.DataFrame({
    "Emri": ["Ana", "Jon", "Sara"],
    "Paga": [800, np.nan, 1200]
})

df_with_nan

   Emri    Paga
0   Ana   800.0
1   Jon     NaN
2  Sara  1200.0

In [20]:
df_with_nan.isna()

    Emri   Paga
0  False  False
1  False   True
2  False  False

In [21]:
df_with_nan.isna().sum()

Emri    0
Paga    1
dtype: int64

In [22]:
df

    Emri Departamenti  Paga
0    Ana           IT   800
1    Jon      Finance  1200
2   Sara           IT   700
3   Elio           HR  1000
4   Dora      Finance  1500
5  Ardit           IT   950

## Grupim: mesatarja sipas departamentit
Kjo është një nga operacionet më të përdorura në praktikë.

In [23]:
data = {
    "Emri": ["Ana", "Jon", "Sara", "Elio", "Dora", "Ardit"],
    "Mosha": [25, 30, 22, 28, 35, 27],
    "Departamenti": ["IT", "Finance", "IT", "HR", "Finance", "IT"],
    "Paga": [800, 1200, 700, 1000, 1500, 950]
}

df = pd.DataFrame(data)
df.groupby(["Departamenti", 'Mosha'])["Paga"].mean()

Departamenti  Mosha
Finance       30       1200.0
              35       1500.0
HR            28       1000.0
IT            22        700.0
              25        800.0
              27        950.0
Name: Paga, dtype: float64

## Punë me CSV (si në jetë reale)

Në praktikë, të dhënat shpesh vijnë si CSV.
Më poshtë do të krijojmë një CSV të vogël dhe pastaj do ta lexojmë me Pandas.
Kjo na ndihmon të kuptojmë workflow-n real.

In [24]:

products_df = pd.read_csv("../data/products.csv")
products_df

      Produkti    Kategoria  Cmimi
0      Telefon  Elektronikë   1568
1        Kufje  Elektronikë    507
2       Tablet         Zyrë    259
3       Kamerë  Elektronikë   1259
4     Tastierë  Elektronikë    111
5      Telefon  Elektronikë    526
6       Kamerë         Zyrë    104
7       Kamerë  Elektronikë   1516
8       Kamerë     Aksesorë    501
9      Printer         Zyrë    619
10      Laptop  Elektronikë   1479
11    Tastierë     Aksesorë    619
12      Tablet  Elektronikë   1613
13       Mouse  Elektronikë    239
14    Tastierë  Elektronikë    785
15       Mouse         Zyrë    591
16      Laptop         Zyrë    990
17      Kamerë  Elektronikë   1938
18    Tastierë  Elektronikë   1180
19       Kufje         Zyrë   1316
20       Mouse         Zyrë    443
21     Telefon  Elektronikë   1404
22     Monitor     Aksesorë    213
23     Monitor  Elektronikë    828
24       Kufje     Aksesorë   1351
25       Mouse  Elektronikë    808
26       Mouse  Elektronikë   1422
27       Kufje         Zyrë   1968
28     Telefon         Zyrë   1350
29      Tablet         Zyrë   1543
30     Monitor  Elektronikë    996
31    Tastierë     Aksesorë   1945
32      Kamerë  Elektronikë   1452
33       Mouse  Elektronikë    519
34      Laptop     Aksesorë    871
35       Kufje  Elektronikë    482
36  Smartwatch         Zyrë    694
37     Monitor         Zyrë   1072
38    Tastierë         Zyrë    989
39      Tablet     Aksesorë    335
40     Monitor         Zyrë   1199
41      Kamerë     Aksesorë   1579
42  Smartwatch     Aksesorë   1888
43  Smartwatch     Aksesorë    791
44     Monitor  Elektronikë   1093
45     Printer  Elektronikë   1597
46      Laptop  Elektronikë    363
47      Tablet         Zyrë    914
48  Smartwatch  Elektronikë    838
49    Tastierë         Zyrë   1008

## Practice Time 🧠

### Ushtrimi 1 (Leximi & Eksplorimi i të Dhënave)
1. Lexoni CSV file-in në një DataFrame
2. Shfaqni 5 rreshtat e parë
3. Shfaqni informacionin e DataFrame-it
4. Shfaqni statistikat bazë për kolonën Cmimi

### Ushtrimi 2 (Filtrimi & Renditja)
1. Filtroni produktet me Cmimi > 1000
2. Renditni rezultatet sipas kolonës Cmimi (nga më e madhja te më e vogla)
3. Shfaqni vetëm kolonat:
   -Produkti
   -Cmimi

### Ushtrimi 3 (CSV)
1. Ruaje DataFrame-in si CSV
2. Lexoje përsëri nga CSV dhe shfaq head()

### Bonus (Analizë e Shpejtë)
1. Sa produkte ka në secilën kategori?
2. Cila kategori ka çmimin mesatar më të lartë?